Repository Bramgus12/ProjectD, pull requests merged in 2020-05, with the labels that each got.

#10 Detail screen plants
  client/assets/images/croton.jpg
  client/assets/images/dracaena_lemon_lime.jpg
  client/assets/images/peace_lily.jpg
  client/assets/images/pothos.jpg
  client/assets/images/snake_plant.jpg
  client/lib/main.dart
  client/lib/pages/PlantList.dart
  client/lib/pages/plant-detail.dart
  client/pubspec.yaml
Labels: enhancement

#7 Added install instructions for back end.
  README.md
Labels: documentation

#9 Created Unit tests and updates to the WeatherController
  server/build.gradle
  server/src/main/java/com/bylivingart/plants/AuthenticationEntryPoint.java
  server/src/main/java/com/bylivingart/plants/DatabaseConnection.java
  server/src/main/java/com/bylivingart/plants/PlantsApplication.java
  server/src/main/java/com/bylivingart/plants/ScheduledTaks.java
  server/src/main/java/com/bylivingart/plants/SwaggerConfig.java
  server/src/main/java/com/bylivingart/plants/buienradar/IcoonactueelType.java
  server/src/main/java/com/bylivingart/plants/buienradar/StationnaamType.java
  server/src/main/java/com/bylivingart/plants/buienradar/WeerstationType.java
  server/src/main/java/com/bylivingart/plants/controllers/UserController.java
  server/src/main/java/com/bylivingart/plants/controllers/WeatherController.java
  server/src/main/java/com/bylivingart/plants/dataclasses/Error.java
  server/src/main/java/com/bylivingart/plants/statements/UserStatements.java
  server/src/main/java/com/bylivingart/plants/statements/WeatherStatements.java
  server/src/test/java/com/bylivingart/plants/controllers/WeatherControllerTests.java
Labels: enhancement

#14 Created tables for user_plants and plants.
  .gitignore
  client/.gitignore
  client/.idea/codeStyles/Project.xml
  client/.idea/misc.xml
  client/.idea/vcs.xml
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/bylivingart/plants/FileService.java
  server/src/main/java/com/bylivingart/plants/GetPropertyValues.java
  server/src/main/java/com/bylivingart/plants/ScheduledTask.java
  server/src/main/java/com/bylivingart/plants/controllers/PlantsController.java
  server/src/main/java/com/bylivingart/plants/controllers/UserPlantsController.java
  server/src/main/java/com/bylivingart/plants/controllers/WeatherController.java
  server/src/main/java/com/bylivingart/plants/dataclasses/Plants.java
  server/src/main/java/com/bylivingart/plants/dataclasses/UserPlants.java
  server/src/main/java/com/bylivingart/plants/statements/PlantsStatements.java
  server/src/main/java/com/bylivingart/plants/statements/UserPlantsStatements.java
  server/src/main/resources/Database_config.properties.example
  server/src/main/resources/file_path.properties
  server/src/main/resources/photos/.gitkeep
  server/src/main/resources/plants/.gitkeep
  server/src/test/java/com/bylivingart/plants/controllers/WeatherControllerTests.java
Labels: enhancement

#20 Extended user
  README.md
  server/.gitignore
  server/build.gradle
  server/local.properties
  server/src/main/java/com/bylivingart/plants/FileService.java
  server/src/main/java/com/bylivingart/plants/HandleException.java
  server/src/main/java/com/bylivingart/plants/SecurityConfig.java
  server/src/main/java/com/bylivingart/plants/controllers/PlantsController.java
  server/src/main/java/com/bylivingart/plants/controllers/UserController.java
  server/src/main/java/com/bylivingart/plants/controllers/UserPlantsController.java
  server/src/main/java/com/bylivingart/plants/controllers/WeatherController.java
  server/src/main/java/com/bylivingart/plants/dataclasses/User.java
  server/src/main/java/com/bylivingart/plants/statements/PlantsStatements.java
  server/src/main/java/com/bylivingart/plants/statements/UserPlantsStatements.java
  server/src/main/java/com/bylivingart/plants/statements/UserStatements.java
  server/src/main/java/com/bylivingart/plants/statements/WeatherStatements.java
  server/src/main/resources/application.properties
Labels: documentation, enhancement

#22 Model api connection
  client/assets/cfg/debug.json
  client/assets/images/-1.jpg
  client/assets/images/10.jpg
  client/assets/images/11.jpg
  client/assets/images/12.jpg
  client/assets/images/7.jpg
  client/assets/images/9.jpg
  client/assets/label.txt
  client/lib/api/ApiConnection.dart
  client/lib/pages/Camera.dart
  client/pubspec.yaml
Labels: enhancement
